language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
    - python: "pypy"
    - python: "nightly"
before_install:
  # download FFmpeg Linux static build linked from FFmpeg's official download page
  - wget http://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz
  - tar -xJf ffmpeg-git-64bit-static.tar.xz
  - mv ffmpeg-git-*/ ffmpeg/
  - export PATH=$PWD/ffmpeg:$PATH
install:
  - pip install -r requirements.txt -r tests/requirements.txt -r docs/requirements.txt .
script:
  - nosetests --verbose --exe --with-coverage --cover-erase --cover-package=storyboard --with-doctest
  - cd docs && make html && cd ..
after_success:
  - coveralls
