language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
before_install:
  # download FFmpeg Linux static build linked from FFmpeg's official download page
  - wget http://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz
  - tar -xJf ffmpeg-git-64bit-static.tar.xz
  - mv ffmpeg-git-*/ ffmpeg/
  - export PATH=$PWD/ffmpeg:$PATH
install:
  - pip install Pillow
  - pip install coveralls
script:
  - coverage run --source=storyboard setup.py test
after_success:
  - coveralls
