# Adapted from http://git.io/vfLvX
# More info: Building Binary Wheels for Windows using Appveyor
#            https://packaging.python.org/en/latest/appveyor.html

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python32"
      PYTHON_VERSION: "3.2.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.0"

    - PYTHON: "C:\\Python32-x64"
      PYTHON_VERSION: "3.2.6"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3.6"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.1"

init:
  - git config --global core.autocrlf input
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - cinst ffmpeg
  - powershell .appveyor\install.ps1
  - pip install -r requirements.txt
  - pip install -r tests\requirements.txt
  - pip install -r docs\requirements.txt
  - pip install .

build: off

test_script:
  - nosetests --verbose --exe --with-coverage --cover-erase --cover-package=storyboard --with-doctest
  - cd docs
  - .\make.bat html
  - cd ..
