# Adapted from https://github.com/pypa/python-packaging-user-guide/blob/master/source/code/appveyor.yml
# More info: Building Binary Wheels for Windows using Appveyor
#            https://packaging.python.org/en/latest/appveyor.html

environment:
  matrix:
    # https://www.appveyor.com/docs/build-environment/#python
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

init:
  - git config --global core.autocrlf input
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - git submodule update --init --recursive
  - cinst -y ffmpeg
  - powershell .appveyor\install.ps1
  - set PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%
  - pip install -r requirements.txt -r tests\requirements.txt -r docs\requirements.txt .
  # There seems to be a bug in the ffprobe installed by AppVeyor
  # (using cinst) that always run into an infinite loop when
  # processing vp9.webm with -show_frames.  See
  # https://ci.appveyor.com/project/zmwangx/storyboard/build/1.0.50,
  # and especially the log file
  # https://ci.appveyor.com/api/buildjobs/n7e9dakb5ivsaxee/log for the
  # presence of the infinite loop.
  - del .\tests\more\samples\vp9.webm .\tests\more\samples\vp9.webm.out

build: off

test_script:
  - nosetests --verbose --exe --with-coverage --cover-erase --cover-package=storyboard --with-doctest
  - cd docs
  - make.bat html
  - cd ..
