# Adapted from http://git.io/vfLvX
# More info: Building Binary Wheels for Windows using Appveyor
#            https://packaging.python.org/en/latest/appveyor.html

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.11"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.1"
      PYTHON_ARCH: "32"

init:
  - git config --global core.autocrlf input
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - git submodule update --init --recursive
  - cinst -y ffmpeg
  - powershell .appveyor\install.ps1
  - set PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%
  - pip install -r requirements.txt -r tests\requirements.txt -r docs\requirements.txt .
  # There seems to be a bug in the ffprobe installed by AppVeyor
  # (using cinst) that always run into an infinite loop when
  # processing vp9.webm with -show_frames.  See
  # https://ci.appveyor.com/project/zmwangx/storyboard/build/1.0.50,
  # and especially the log file
  # https://ci.appveyor.com/api/buildjobs/n7e9dakb5ivsaxee/log for the
  # presence of the infinite loop.
  - del .\tests\more\samples\vp9.webm .\tests\more\samples\vp9.webm.out

build: off

test_script:
  - nosetests --verbose --exe --with-coverage --cover-erase --cover-package=storyboard --with-doctest
  - cd docs
  - make.bat html
  - cd ..
