# Adapted from http://git.io/vfLvX
# More info: Building Binary Wheels for Windows using Appveyor
#            https://packaging.python.org/en/latest/appveyor.html

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python32"
      PYTHON_VERSION: "3.2.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "32"

init:
  - git config --global core.autocrlf input
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - git submodule update --init --recursive
  - cinst ffmpeg
  - powershell .appveyor\install.ps1
  - set PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%
  - pip install -r requirements.txt -r tests\requirements.txt -r docs\requirements.txt .

build: off

test_script:
  - nosetests --verbose --exe --with-coverage --cover-erase --cover-package=storyboard --with-doctest
  - cd docs
  - make.bat html
  - cd ..
